"""Add Customer Table & Update Budget Item Schema

Revision ID: 61db2469ac5c
Revises: 4d2a320893fe
Create Date: 2021-04-07 11:49:44.793534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61db2469ac5c'
down_revision = '4d2a320893fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('budget_item', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('budget_item', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('budget_item', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('budget_item', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('budget_item', sa.Column('name', sa.String(length=140), nullable=True))
    op.drop_index('ix_budget_item_timestamp', table_name='budget_item')
    op.create_index(op.f('ix_budget_item_date_created'), 'budget_item', ['date_created'], unique=False)
    op.create_index(op.f('ix_budget_item_date_modified'), 'budget_item', ['date_modified'], unique=False)
    op.create_foreign_key(None, 'budget_item', 'customer', ['customer_id'], ['id'])
    op.drop_column('budget_item', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_item', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'budget_item', type_='foreignkey')
    op.drop_index(op.f('ix_budget_item_date_modified'), table_name='budget_item')
    op.drop_index(op.f('ix_budget_item_date_created'), table_name='budget_item')
    op.create_index('ix_budget_item_timestamp', 'budget_item', ['timestamp'], unique=False)
    op.drop_column('budget_item', 'name')
    op.drop_column('budget_item', 'date_modified')
    op.drop_column('budget_item', 'date_created')
    op.drop_column('budget_item', 'customer_id')
    op.drop_column('budget_item', 'amount')
    op.drop_table('customer')
    # ### end Alembic commands ###
