"""Update Budget Item Schema Timestamp Defaults

Revision ID: cd3abd25a15a
Revises: 61db2469ac5c
Create Date: 2021-04-07 11:52:45.290700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd3abd25a15a'
down_revision = '61db2469ac5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_item', 'amount',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('budget_item', 'date_created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('budget_item', 'date_modified',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_item', 'date_modified',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('budget_item', 'date_created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('budget_item', 'amount',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
